version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mariadb_data:/home/db/mysql
      - ./mariadb/custom.cnf:/etc/mysql/mariadb.conf.d/99-custom.cnf
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgrespass
    volumes:
      - postgres_data:/home/db/postgres
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - backend

  wordpress:
    image: wordpress:php7.4-apache
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: newpassword
      WORDPRESS_DB_NAME: testdb
    volumes:
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - mariadb
    networks:
      - backend

volumes:
  mariadb_data:
  postgres_data:

networks:
  backend: