version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: lab_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - ./home/db/mysql:/var/lib/mysql   
    ports:
      - "127.0.0.1:3306:3306" 
    networks:
      - db_network
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=20
      - --wait_timeout=10
      - --bind-address=127.0.0.1 
    user: "1000:1000"  

  postgres:
    image: postgres:latest
    container_name: lab_postgres
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    volumes:
      - ./home/db/postgres:/var/lib/postgresql/data 
    ports:
      - "127.0.0.1:5432:5432" 
    networks:
      - db_network
    command: 
      - -c
      - max_connections=20
      - -c
      - idle_in_transaction_session_timeout=10000
      - -c
      - listen_addresses=127.0.0.1  
    user: "1000:1000"  

  wordpress:
    image: wordpress:latest
    container_name: lab_wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: lab_mariadb:3306
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: testpassword
      WORDPRESS_DB_NAME: testdb
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - db_network
    restart: unless-stopped


networks:
  db_network:
    driver: bridge